CREATE TABLE IF NOT EXISTS addresses (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label VARCHAR(50) NOT NULL,
    street VARCHAR(255) NOT NULL,
    number VARCHAR(20) NOT NULL,
    colony VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    country VARCHAR(100) NOT NULL,
    reference VARCHAR(500),
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_id INTEGER REFERENCES addresses(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_street VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_number VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_colony VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_city VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_state VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_zip_code VARCHAR(10);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_country VARCHAR(100);
